/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IContributorsDelegation,
  IContributorsDelegationInterface,
} from "../IContributorsDelegation";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_delegated",
        type: "address",
      },
    ],
    name: "isDelegatedOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IContributorsDelegation__factory {
  static readonly abi = _abi;
  static createInterface(): IContributorsDelegationInterface {
    return new utils.Interface(_abi) as IContributorsDelegationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IContributorsDelegation {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IContributorsDelegation;
  }
}
