/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IContributors, IContributorsInterface } from "../IContributors";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IContributors__factory {
  static readonly abi = _abi;
  static createInterface(): IContributorsInterface {
    return new utils.Interface(_abi) as IContributorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IContributors {
    return new Contract(address, _abi, signerOrProvider) as IContributors;
  }
}
